# -*- coding: utf-8 -*-

version: '3.6'

# ####################################################################
# AK8PO Weather Mapper
# Filip Findura
# ####################################################################

services:

  # ----------------------------
  # Database (PostgreSQL)
  # ----------------------------
  database:
    image: postgres
    container_name: postgres
    restart: on-failure
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'weather'
      # Timezone correction in Docker (Etc/UTC -> Europe/Prague)
      TZ: 'Europe/Prague'

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: on-failure
    ports:
      - "5050:80"
    volumes:
      - pgadmindata:/var/lib/pgadmin
    environment:
      # Login to pgAdmin:
      PGADMIN_DEFAULT_EMAIL: 'root@pgadmin.cz'
      PGADMIN_DEFAULT_PASSWORD: 'postgres'
      # Timezone correction in Docker (Etc/UTC -> Europe/Prague)
      TZ: 'Europe/Prague'

  # ----------------------------
  # Frontend
  # ----------------------------
  frontend:
    image: frontend
    build: ./frontend
    container_name: frontend
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - backend

  # ----------------------------
  # Backend
  # ----------------------------
  backend:
    image: backend
    build: ./backend
    container_name: backend
    restart: on-failure
    environment:
      TODO: foo
    ports:
      - "8081:8080"
    depends_on:
      - database

# ####################################################################
# Data persistence
# ####################################################################

volumes:
  # Database
  pgdata:
    driver: local
  pgadmindata:
    driver: local
