{
 "title": "Weather Forecast Comparison",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "30m",
 "panels": [
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(forecast_time,$__interval),\n  avg(temperature) AS \"Weather API\"\nFROM weather_data\nWHERE\n  $__timeFilter(forecast_time) AND\n  datasource = 'weatherapi'\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(forecast_time,$__interval),\n  avg(temperature) AS \"Norwegian Meteorological Institute\"\nFROM weather_data\nWHERE\n  $__timeFilter(forecast_time) AND\n  datasource = 'nmi'\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(forecast_time,$__interval),\n  avg(temperature) AS \"Open Weather Map\"\nFROM weather_data\nWHERE\n  $__timeFilter(forecast_time) AND\n  datasource = 'owm'\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(forecast_time,$__interval),\n  avg(temperature) AS \"Weather Stack\"\nFROM weather_data\nWHERE\n  $__timeFilter(forecast_time) AND\n  datasource = 'weatherstack'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Precipitation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "lengthmm" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(forecast_time,$__interval),\n  avg(precipitations) AS \"Weather API\"\nFROM weather_data\nWHERE\n  $__timeFilter(forecast_time) AND\n  datasource = 'weatherapi'\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(forecast_time,$__interval),\n  avg(precipitations) AS \"Norwegian Meteorological Institute\"\nFROM weather_data\nWHERE\n  $__timeFilter(forecast_time) AND\n  datasource = 'nmi'\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(forecast_time,$__interval),\n  avg(precipitations) AS \"Open Weather Map\"\nFROM weather_data\nWHERE\n  $__timeFilter(forecast_time) AND\n  datasource = 'owm'\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(forecast_time,$__interval),\n  avg(precipitations) AS \"Weather Stack\"\nFROM weather_data\nWHERE\n  $__timeFilter(forecast_time) AND\n  datasource = 'weatherstack'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Wind speed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "velocitykmh" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(forecast_time,$__interval),\n  avg(wind_speed) AS \"Weather API\"\nFROM weather_data\nWHERE\n  $__timeFilter(forecast_time) AND\n  datasource = 'weatherapi'\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(forecast_time,$__interval),\n  avg(wind_speed) AS \"Norwegian Meteorological Institute\"\nFROM weather_data\nWHERE\n  $__timeFilter(forecast_time) AND\n  datasource = 'nmi'\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(forecast_time,$__interval),\n  avg(wind_speed) AS \"Open Weather Map\"\nFROM weather_data\nWHERE\n  $__timeFilter(forecast_time) AND\n  datasource = 'owm'\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(forecast_time,$__interval),\n  avg(wind_speed) AS \"Weather Stack\"\nFROM weather_data\nWHERE\n  $__timeFilter(forecast_time) AND\n  datasource = 'weatherstack'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(forecast_time,$__interval),\n  avg(humidity) AS \"Weather API\"\nFROM weather_data\nWHERE\n  $__timeFilter(forecast_time) AND\n  datasource = 'weatherapi'\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(forecast_time,$__interval),\n  avg(humidity) AS \"Norwegian Meteorological Institute\"\nFROM weather_data\nWHERE\n  $__timeFilter(forecast_time) AND\n  datasource = 'nmi'\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(forecast_time,$__interval),\n  avg(humidity) AS \"Open Weather Map\"\nFROM weather_data\nWHERE\n  $__timeFilter(forecast_time) AND\n  datasource = 'owm'\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(forecast_time,$__interval),\n  avg(humidity) AS \"Weather Stack\"\nFROM weather_data\nWHERE\n  $__timeFilter(forecast_time) AND\n  datasource = 'weatherstack'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "pressurehpa" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(forecast_time,$__interval),\n  avg(pressure) AS \"Weather API\"\nFROM weather_data\nWHERE\n  $__timeFilter(forecast_time) AND\n  datasource = 'weatherapi'\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(forecast_time,$__interval),\n  avg(pressure) AS \"Norwegian Meteorological Institute\"\nFROM weather_data\nWHERE\n  $__timeFilter(forecast_time) AND\n  datasource = 'nmi'\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(forecast_time,$__interval),\n  avg(pressure) AS \"Open Weather Map\"\nFROM weather_data\nWHERE\n  $__timeFilter(forecast_time) AND\n  datasource = 'owm'\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(forecast_time,$__interval),\n  avg(pressure) AS \"Weather Stack\"\nFROM weather_data\nWHERE\n  $__timeFilter(forecast_time) AND\n  datasource = 'weatherstack'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Cloud fraction",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(forecast_time,$__interval),\n  avg(cloud_fraction) AS \"Weather API\"\nFROM weather_data\nWHERE\n  $__timeFilter(forecast_time) AND\n  datasource = 'weatherapi'\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(forecast_time,$__interval),\n  avg(cloud_fraction) AS \"Norwegian Meteorological Institute\"\nFROM weather_data\nWHERE\n  $__timeFilter(forecast_time) AND\n  datasource = 'nmi'\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(forecast_time,$__interval),\n  avg(cloud_fraction) AS \"Open Weather Map\"\nFROM weather_data\nWHERE\n  $__timeFilter(forecast_time) AND\n  datasource = 'owm'\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(forecast_time,$__interval),\n  avg(cloud_fraction) AS \"Weather Stack\"\nFROM weather_data\nWHERE\n  $__timeFilter(forecast_time) AND\n  datasource = 'weatherstack'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  }
 ]
}